services:
  postgresql-db:
    image: postgres:17.10
    container_name: postgresql-db
    restart: unless-stopped
    environment:
        # Use password for postgres user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'postgresql-db:/var/lib/postgresql/data'
    ports:
      - '5433:5432'

  postgresql-test-db:
    image: postgres:17.10
    container_name: postgresql-test-db
    restart: unless-stopped
    environment:        
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
    volumes:
      - 'postgresql-test-db:/var/lib/postgresql/data'
    ports:
      - '5434:5432'

  redis-db:
    image: redis:8.10.0-alpine
    container_name: redis-db
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - 'redis-db:/data'
    ports:
      - '6379:6379'

  backend:
    build: .
    container_name: layermed-backend
    restart: unless-stopped
    depends_on:
      - postgresql-db
      - redis-db
    command: >
      sh -c "alembic upgrade head &&
             python -m src.services.seed &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgresql-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
      REDIS_HOST: redis-db
      REDIS_PORT: 6379

      KEY: ${KEY}
      ALGORITHM: ${ALGORITHM}
      TOKEN_EXPIRE: ${TOKEN_EXPIRE}

volumes:
  postgresql-db:
  postgresql-test-db:
  redis-db: