services:
  postgresql-app:
    image: postgres:17.10
    container_name: postgresql-db
    environment:
        # Use password for postgres user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'postgresql-db:/var/lib/postgresql/data'
    ports:
      - '5433:5432'

  redis-app:
    image: redis:8.10.0-alpine
    container_name: redis-app
    volumes:
      - 'redis-db:/data'
    ports:
      - '6379:6379'

  backend:
    build: .
    container_name: layermed-backend
    restart: always
    depends_on:
      - postgresql-app
      - redis-app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgresql-app
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
      REDIS_HOST: redis-app
      REDIS_PORT: 6379

      KEY: ${KEY}
      ALGORITHM: ${ALGORITHM}
      TOKEN_EXPIRE: ${TOKEN_EXPIRE}

volumes:
  postgresql-db:
  redis-db: