[project]
name = "layermed-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.0",
    "asyncpg>=0.31.0",
    "bcrypt==4.0.1",
    "fastapi>=0.141.1",
    "fastapi-cache2[redis]>=0.1.8",
    "jwt>=1.4.0",
    "loguru>=0.7.3",
    "passlib>=1.7.4",
    "pip>=26.2.1",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.14.2",
    "pydantic[all,email]>=2.13.4",
    "pyjwt>=2.13.0",
    "pyright>=1.1.411",
    "redis>=8.1.0",
    "ruff>=0.16.1",
    "setuptools>=83.0.0",
    "sqlalchemy>=2.0.51",
]


[tool.pyright]
typeCheckingMode='standard'
