"""update images filed in offers table

Revision ID: 09fac1b6484b
Revises: 48c257592bb4
Create Date: 2026-09-07 13:48:31.854147

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09fac1b6484b"
down_revision: str | Sequence[str] | None = "48c257592bb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE offers SET images = '{}' WHERE images IS NULL")
    op.alter_column("offers", "images", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("offers", "images", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
