"""add_cities_table_with_dependences

Revision ID: 0e68a2041c8c
Revises: 29e15bed51af
Create Date: 2026-08-11 11:41:09.291543

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e68a2041c8c"
down_revision: str | Sequence[str] | None = "29e15bed51af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:

    bookstatus_enum = postgresql.ENUM(
        "PENDING", "CONFIRMED", "CANCELLED", "COMPLETED", "NO_SHOW", name="bookstatus"
    )

    bookstatus_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "cities",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "bookings",
        sa.Column("appointment_time", sa.TIMESTAMP(timezone=True), nullable=False),
    )

    op.alter_column(
        "bookings",
        "status",
        existing_type=sa.VARCHAR(),
        type_=bookstatus_enum,
        postgresql_using="status::bookstatus",
        existing_nullable=False,
    )

    op.drop_column("bookings", "book_type")
    op.add_column("suggestions", sa.Column("city_id", sa.Integer(), nullable=False))
    op.add_column("suggestions", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_suggestions_title_cost_format"), table_name="suggestions")
    op.create_index(
        "ix_suggestions_title_cost_format",
        "suggestions",
        ["city_id", "title", "cost", "suggest_format"],
        unique=False,
    )
    op.create_foreign_key(None, "suggestions", "cities", ["city_id"], ["id"])
    op.drop_column("suggestions", "city")
    op.add_column("users", sa.Column("city_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "users", "cities", ["city_id"], ["id"])
    op.drop_column("users", "city")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "city_id")
    op.add_column(
        "suggestions",
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "suggestions", type_="foreignkey")
    op.drop_index("ix_suggestions_title_cost_format", table_name="suggestions")
    op.create_index(
        op.f("ix_suggestions_title_cost_format"),
        "suggestions",
        ["title", "cost", "suggest_format"],
        unique=False,
    )
    op.drop_column("suggestions", "is_active")
    op.drop_column("suggestions", "city_id")
    op.add_column(
        "bookings",
        sa.Column("book_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "bookings",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "CONFIRMED",
            "CANCELLED",
            "COMPLETED",
            "NO_SHOW",
            name="bookstatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("bookings", "appointment_time")
    op.drop_table("cities")
    bookstatus_enum = postgresql.ENUM(
        "PENDING", "CONFIRMED", "CANCELLED", "COMPLETED", "NO_SHOW", name="bookstatus"
    )
    bookstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
