"""rename suggestion module to offer

Revision ID: 10f7af3afaf1
Revises: c4c72ee85c12
Create Date: 2026-08-31 13:39:07.328734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10f7af3afaf1'
down_revision: Union[str, Sequence[str], None] = 'c4c72ee85c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

moderation_status_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus') 
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    moderation_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('offers',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('suggest_format', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_title_cost_format', 'offers', ['city_id', 'title', 'cost', 'suggest_format'], unique=False)
    op.create_table('offer_symptoms',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['symptom_id'], ['offers.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('offer_id', 'symptom_id')
    )
    op.create_index('idx_symptom_offer', 'offer_symptoms', ['symptom_id', 'offer_id'], unique=False)
    op.add_column('bookings', sa.Column('offer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'offers', ['offer_id'], ['id'], ondelete='cascade')
    op.drop_column('bookings', 'suggestion_id')
    op.execute("ALTER TABLE doctors ALTER COLUMN status TYPE moderationstatus USING status::moderationstatus")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE doctors ALTER COLUMN status TYPE VARCHAR USING status::text")
    op.add_column('bookings', sa.Column('suggestion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'offer_id')
    op.drop_index('idx_symptom_offer', table_name='offer_symptoms')
    op.drop_table('offer_symptoms')
    op.drop_index('ix_offers_title_cost_format', table_name='offers')
    op.drop_table('offers')
    moderation_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
