"""rename_specialty_id_field

Revision ID: 1da26c615af1
Revises: d13438ced094
Create Date: 2026-08-13 19:00:50.004803

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1da26c615af1'
down_revision: str | Sequence[str] | None = 'd13438ced094'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_specialties', sa.Column('specialty_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('doctor_specialties_speciality_id_fkey'), 'doctor_specialties', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_specialties', 'specialties', ['specialty_id'], ['id'], ondelete='cascade')
    op.drop_column('doctor_specialties', 'speciality_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_specialties', sa.Column('speciality_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'doctor_specialties', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_specialties_speciality_id_fkey'), 'doctor_specialties', 'specialties', ['speciality_id'], ['id'], ondelete='CASCADE')
    op.drop_column('doctor_specialties', 'specialty_id')
    # ### end Alembic commands ###
