"""create_specialty_tabels

Revision ID: 274c2f710f08
Revises: c5621f3293e8
Create Date: 2026-08-13 16:52:22.185528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274c2f710f08'
down_revision: Union[str, Sequence[str], None] = 'c5621f3293e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('specialty_id', sa.Integer(), nullable=False))
    op.add_column('doctors', sa.Column('education', sa.String(), nullable=False))
    op.drop_index(op.f('ix_doctors_speciality_exp'), table_name='doctors')
    op.create_index('ix_doctors_speciality_exp', 'doctors', ['specialty_id', 'education', 'experience_years'], unique=False)
    op.drop_column('doctors', 'educational')
    op.drop_column('doctors', 'speciality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('speciality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('educational', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_doctors_speciality_exp', table_name='doctors')
    op.create_index(op.f('ix_doctors_speciality_exp'), 'doctors', ['speciality', 'educational', 'experience_years'], unique=False)
    op.drop_column('doctors', 'education')
    op.drop_column('doctors', 'specialty_id')
    # ### end Alembic commands ###
