"""add_symptoms_tables

Revision ID: 29e15bed51af
Revises: da6c91c422ab
Create Date: 2026-08-10 19:03:00.862154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e15bed51af'
down_revision: Union[str, Sequence[str], None] = 'da6c91c422ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('city', sa.String(), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('suggestions', 'city')
    # ### end Alembic commands ###
