"""create_city_id_optional_field

Revision ID: 2bf3c928ed89
Revises: 51a568d4d170
Create Date: 2026-08-13 14:37:39.742677

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bf3c928ed89"
down_revision: str | Sequence[str] | None = "51a568d4d170"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "city_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "city_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
