"""create new field in offer table

Revision ID: 309e614890bb
Revises: 57b21011bbf5
Create Date: 2026-08-31 15:43:53.090472

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "309e614890bb"
down_revision: str | Sequence[str] | None = "57b21011bbf5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
