"""remove_id_from_suggestion_symptoms

Revision ID: 346b36a57a28
Revises: 3ac3d668cbac
Create Date: 2026-08-12 16:22:02.657118

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "346b36a57a28"
down_revision: str | Sequence[str] | None = "3ac3d668cbac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suggestion_symptoms", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "suggestion_symptoms",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
