"""add_symptoms_tabels

Revision ID: 3ac3d668cbac
Revises: 0e68a2041c8c
Create Date: 2026-08-12 16:18:02.906109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac3d668cbac'
down_revision: Union[str, Sequence[str], None] = '0e68a2041c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion_symptoms',
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('symptome_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['symptome_id'], ['symptoms.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('suggestion_id', 'symptome_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion_symptoms')
    op.drop_table('symptoms')
    # ### end Alembic commands ###
