"""remove_doctor_from_bookings_and_add_dob_to_users

Revision ID: 489f333f60ad
Revises: c59a37d477df
Create Date: 2026-08-09 13:43:16.258478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489f333f60ad'
down_revision: Union[str, Sequence[str], None] = 'c59a37d477df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_doctor_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'doctor_id')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.create_foreign_key(op.f('bookings_doctor_id_fkey'), 'bookings', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
