"""add rejection_reason to offers

Revision ID: 48c257592bb4
Revises: 309e614890bb
Create Date: 2026-09-01 10:42:46.768121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c257592bb4'
down_revision: Union[str, Sequence[str], None] = '309e614890bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'rejection_reason')
    # ### end Alembic commands ###
