"""add status column to reviews table

Revision ID: 548d0f7c8c35
Revises: 796edab9bc6e
Create Date: 2026-08-30 15:11:59.367973

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "548d0f7c8c35"
down_revision: str | Sequence[str] | None = "796edab9bc6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "status")
    # ### end Alembic commands ###
