"""remade offer table fields

Revision ID: 57b21011bbf5
Revises: 3b85d1a1cd49
Create Date: 2026-08-31 14:30:57.942970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57b21011bbf5'
down_revision: Union[str, Sequence[str], None] = '3b85d1a1cd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('CLINIC', 'ONLINE', 'HOME_VISIT', 'CHAT', name='offerformat').create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'doctors', 
        'status',
        existing_type=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='doctorstatus'),
        type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus'),
        existing_nullable=False,
        postgresql_using='status::text::moderationstatus'
    )

    op.add_column('offers', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus'), nullable=False))
    op.add_column('offers', sa.Column('offer_format', sa.Enum('CLINIC', 'ONLINE', 'HOME_VISIT', 'CHAT', name='offerformat'), nullable=False))
    op.add_column('offers', sa.Column('images', sa.String(), nullable=True))
    op.drop_index(op.f('ix_offers_title_cost_format'), table_name='offers')
    op.create_index('ix_offers_title_cost_format', 'offers', ['city_id', 'title', 'cost', 'offer_format'], unique=False)
    op.drop_column('offers', 'duration')
    op.drop_column('offers', 'is_active')
    op.drop_column('offers', 'suggest_format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('suggest_format', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_offers_title_cost_format', table_name='offers')
    op.create_index(op.f('ix_offers_title_cost_format'), 'offers', ['city_id', 'title', 'cost', 'suggest_format'], unique=False)
    op.drop_column('offers', 'images')
    op.drop_column('offers', 'offer_format')
    op.drop_column('offers', 'status')
    
    op.alter_column(
        'doctors', 
        'status',
        existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus'),
        type_=postgresql.ENUM('APPROVED', 'PENDING', 'REJECTED', name='doctorstatus'),
        existing_nullable=False,
        postgresql_using='status::text::doctorstatus'
    )
    # ### end Alembic commands ###