"""unique_field_specialty_delete_timestamp

Revision ID: 5e66321408d3
Revises: 1da26c615af1
Create Date: 2026-08-16 17:42:23.715407

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e66321408d3'
down_revision: str | Sequence[str] | None = '1da26c615af1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_specialties', 'created_at')
    op.drop_column('doctor_specialties', 'updated_at')
    op.create_unique_constraint(None, 'specialties', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialties', type_='unique')
    op.add_column('doctor_specialties', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('doctor_specialties', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
