"""add_unique_constraint_to_reviews

Revision ID: 796edab9bc6e
Revises: ffa26646d733
Create Date: 2026-08-29 17:46:57.637373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796edab9bc6e'
down_revision: Union[str, Sequence[str], None] = 'ffa26646d733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_doctor_review'), 'reviews', type_='unique')
    op.drop_column('reviews', 'deletion_reason')
    op.drop_column('reviews', 'is_deletion_requested')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_deletion_requested', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('deletion_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_user_doctor_review'), 'reviews', ['user_id', 'doctor_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
