"""create constraint and enum in Review table

Revision ID: 9e9d9e2bebaf
Revises: d9e2e3406d66
Create Date: 2026-09-13 19:18:09.788408

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e9d9e2bebaf"
down_revision: str | Sequence[str] | None = "d9e2e3406d66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reviews",
        "status",
        existing_type=sa.VARCHAR(),
        type_=postgresql.ENUM(
            "PENDING",
            "APPROVED",
            "REJECTED",
            name="moderationstatus",
            create_type=False,
        ),
        existing_nullable=False,
        postgresql_using="status::moderationstatus",
    )
    op.create_unique_constraint(
        "uq_reviews_doctor_user", "reviews", ["doctor_id", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_reviews_doctor_user", "reviews", type_="unique")
    op.alter_column(
        "reviews",
        "status",
        existing_type=sa.Enum(
            "PENDING", "APPROVED", "REJECTED", name="moderationstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
