"""delete_specialty_id_from_doctor

Revision ID: b07869fc99bd
Revises: 5e66321408d3
Create Date: 2026-08-17 18:28:24.260975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07869fc99bd'
down_revision: Union[str, Sequence[str], None] = '5e66321408d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_speciality_exp'), table_name='doctors')
    op.create_index('ix_doctors_speciality_exp', 'doctors', ['education', 'experience_years'], unique=False)
    op.drop_column('doctors', 'specialty_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('specialty_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_doctors_speciality_exp', table_name='doctors')
    op.create_index(op.f('ix_doctors_speciality_exp'), 'doctors', ['specialty_id', 'education', 'experience_years'], unique=False)
    # ### end Alembic commands ###
