"""add index to suggestion symptom table

Revision ID: c4c72ee85c12
Revises: 548d0f7c8c35
Create Date: 2026-08-30 16:33:47.422924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c72ee85c12'
down_revision: Union[str, Sequence[str], None] = '548d0f7c8c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_symptom_suggestion', 'suggestion_symptoms', ['symptom_id', 'suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symptom_suggestion', table_name='suggestion_symptoms')
    # ### end Alembic commands ###
