"""add_unqie_filed_for_city_name

Revision ID: c5621f3293e8
Revises: 2bf3c928ed89
Create Date: 2026-08-13 15:57:38.254570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5621f3293e8'
down_revision: Union[str, Sequence[str], None] = '2bf3c928ed89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cities', type_='unique')
    # ### end Alembic commands ###
