"""fix_min_into_max_price

Revision ID: ffa26646d733
Revises: c994027af9a7
Create Date: 2026-08-27 18:27:07.975546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa26646d733'
down_revision: Union[str, Sequence[str], None] = 'c994027af9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('max_price', sa.Integer(), nullable=False))
    op.add_column('doctors', sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='doctorstatus'), nullable=False))
    op.add_column('doctors', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.drop_column('doctors', 'min_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('min_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('doctors', 'rejection_reason')
    op.drop_column('doctors', 'status')
    op.drop_column('doctors', 'max_price')
    # ### end Alembic commands ###
